### ISSUE TITLE
buggy behaviour of object positions

### ISSUE THREAD

**Issue by gilbertohasnofb** [pd-l2ork/pd#13]
Sometimes (I couldn't trace in which conditions) moving all objects of a patch to a new position and saving it will not in fact have saved their new positions: next time the patch is opened, all objects are shown on their former position.

One workaround I found on this situations is to move the objects to the desired position and then create some new object such as a [bng] and save the file. Then reopen it and delete the [bng] and save it again. Now all objects are in the desired position.

Below is a sample patch. If I select all objects and move them to the left, save it and then reopen the file, no change will be registered (they will still be in their former position):

--------------------------------------------

#N canvas 710 340 537 261 10;
#X obj 268 27 cnv 15 324 195 empty empty empty 20 12 0 14 -261234 -66577
0;
#X obj 358 34 cnv 30 30 30 empty empty cnv 20 12 0 20 -261234 -66577
0;
#X obj 302 183 hsl 256 15 0 127 0 0 duration duration-receive empty
-2 -8 0 10 -262144 -1 -1 0 1;
#X obj 301 102 bng 30 250 50 0 empty empty empty 35 15 0 10 -262144
-1 -1;
#X text 312 163 comment;

--------------------------------------------

I am using Pd-l2Ork build 20141110 on a 64-bit Linux machine.

**Comment by pd-l2ork** [comment]
The change happens as far as I can tell. It is just that pd-l2ork always
looks to provide you with the optimal view of your patch (meaning as much
as possible being on the screen and visible). When moving everything, you
already have optimal view and then you reposition everything for the
computer to recreate that same optimal view. To check this, you can compare
two patches for differences. New, moved patch should have objects different
than the old patch. Finally, to solidify position on screen, you can use
mycanvas object to delineate desired edges that should be viewable. HTH

**Comment by gilbertohasnofb** [comment]
Thanks for the explanation, indeed there is a difference between a new and a moved patch. You mentioned that I can use [my_canvas] to solidify the position on screen, but how can I do that with that object? I thought [my_canvas] as simply a different name for [cnv], which is just a coloured rectangle. Do you mean to add an invisible white canvas in the background so that pd-l2ork is forced to leave everything inside it on screen?

**Comment by pd-l2ork** [comment]
mycanvas is a synonym for cnv. HTH
