### ISSUE TITLE
Problem with using "control" mesage

### ISSUE THREAD

**Issue by Arseniusz** [pd-l2ork/pd#16]
When I trying to send et.ex "control #1 25" message to my plugin I get error - "unable to send to NULL control path"

**Comment by pd-l2ork** [comment]
Hi, I am not sure what you are trying to do. Are you talking about an et.ex external (I unfortunately never heard of it)? Would you please provide an example patch? BTW #1 arguments are not valid in pd (unlike Max). Perhaps therein lies the problem?
