### ISSUE TITLE
cannot open helpfile for [mrpeach/midifile] 

### ISSUE THREAD

**Issue by gilbertohasnofb** [pd-l2ork/pd#18]
I cannot open helpfile for `[mrpeach/midifile]` (right clicking on this object and selecting Help does nothing in my installation). Also note that the file `midifile-help.pd` can be found at `/usr/lib/pd-l2ork/extra/mrpeach`.

**Comment by pd-l2ork** [comment]
Thank you for the bug report. I just committed a fix to mrpeach's midifile.c that fixes this problem. Marked as resolved.
