### ISSUE TITLE
gcanvas and segmentation fault

### ISSUE THREAD

**Issue by gilbertohasnofb** [pd-l2ork/pd#19]
After creating a `[gcanvas]` object, it work as expected except for the fact that it causes a `Segmentation fault` when I try to move it in Edit mode.

**Comment by pd-l2ork** [comment]
What is a gcanvas?

**Comment by gilbertohasnofb** [comment]
It is an object from the ggee library, but I just found out it is not present in Pd-l2Ork by default. I manually added it from my pd-extended installation some long time ago and I completely forgot about it. In that case, this seg fault is none of your concern as this object is not part of your package, sorry for the wrong report.
