### ISSUE TITLE
Perf mode

### ISSUE THREAD

**Issue by gilbertohasnofb** [pd-l2ork/pd#20]
Pd-extended has a mode (in the Edit menu) called performance mode (or perf mode). Basically it prompts the user if he really wants to close a saved patch or the main program. This avoids that a patch gets closed by accident during a live performance.

This option is not present on Pd-l2Ork. However, the message `[; pd perf 1(` does affect Pd-l2Ork: it makes the program prompt when trying to exit, but it does not prompt the user when closing a saved patch.

Was this feature removed on purpose?

**Comment by pd-l2ork** [comment]
This is not intentional removal, it is simply because pd-l2ork is a fork 
of 0.42.6 and this is something that was introduced into pd-extended at 
a later date. That said, I think this is a cool feature to have, 
although I also think it could be better implemented in a more 
comprehensive way.

Best,

Ico

On 5/2/2015 2:06 PM, Gilberto Agostinho wrote:
>
> Pd-extended has a mode (in the Edit menu) called performance mode (or 
> perf mode). Basically it prompts the user if he really wants to close 
> a saved patch or the main program. This avoids that a patch gets 
> closed by accident during a live performance.
>
> This option is not present on Pd-l2Ork. However, the message |[; pd 
> perf 1(| does affect Pd-l2Ork: it makes the program prompt when trying 
> to exit, but it does not prompt the user when closing a saved patch.
>
> Was the removal of this feature done on purpose?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pd-l2ork/pd/issues/20>.
>

-- 
Ivica Ico Bukvic, D.M.A.
Associate Professor
Computer Music
ICAT Senior Fellow
Director -- DISIS, L2Ork
Virginia Tech
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
ico@vt.edu
www.performingarts.vt.edu
disis.icat.vt.edu
l2ork.icat.vt.edu

**Comment by gilbertohasnofb** [comment]
Ok Ico, in that case should I close this issue?

**Comment by pd-l2ork** [comment]
I would say so, but if it is not too much of a trouble, I would add it 
to our wishlist. We will later implement this in an entirely different 
way, given our toolkit is about to change.

Best,

Ico

On 5/3/2015 11:09 AM, Gilberto Agostinho wrote:
>
> Ok Ico, in that case should I close this issue?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pd-l2ork/pd/issues/20#issuecomment-98491196>.
>

-- 
Ivica Ico Bukvic, D.M.A.
Associate Professor
Computer Music
ICAT Senior Fellow
Director -- DISIS, L2Ork
Virginia Tech
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
ico@vt.edu
www.performingarts.vt.edu
disis.icat.vt.edu
l2ork.icat.vt.edu

**Comment by gilbertohasnofb** [comment]
Ok Ico, I am closing it now. But I don't know how your wishlist work, how can I add it myself?

> our toolkit is about to change

I am very curious about it!

**Comment by pd-l2ork** [comment]
Stay tuned for more info soon ;-)

On 5/3/2015 6:52 PM, Gilberto Agostinho wrote:
>
> Ok Ico, I am closing it now. But I don't know how your wishlist work, 
> how can I add it myself?
>
>     our toolkit is about to change
>
> I am very curious about it!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pd-l2ork/pd/issues/20#issuecomment-98553608>.
>

-- 
Ivica Ico Bukvic, D.M.A.
Associate Professor
Computer Music
ICAT Senior Fellow
Director -- DISIS, L2Ork
Virginia Tech
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
ico@vt.edu
www.performingarts.vt.edu
disis.icat.vt.edu
l2ork.icat.vt.edu
