### ISSUE TITLE
Changing GUI colors (pd-l2ork-x86_64-20150414.deb)

### ISSUE THREAD

**Issue by AMTFA** [pd-l2ork/pd#23]
While changing colors (any preset) the console outputs:

tcl error: invalid command name ".prefs.nb.gui.colors.atom_box.presets.presets"

Nevertheless, the colors are kept for the opened session, but lost when closing Pd-L2Ork.

Is there any way to manually edit color presets? What is the file where colors codes are listed?

**Comment by pd-l2ork** [comment]
This has been fixed in the latest commit. Thank you for the bug report!

**Comment by muranyia** [comment]
With today's sources, I'm still having this problem.

**Comment by pd-l2ork** [comment]
Did you copy new versions of the pd.tk and supporting *.tcl files?

**Comment by muranyia** [comment]
I built using tar_em_up -F and installed by make install. Did I miss something?

**Comment by pd-l2ork** [comment]
That should work. Can you please send me detailed instructions on how to
recreate the error? Thanks.

**Comment by muranyia** [comment]
Sure, open pd-l2ork, go to Edit, Preferences, GUI, click any color button, change the color, click OK, the error appears in the console. Close pd-l2ork, reopen it, the change you made is gone.

I can confirm that pd.tk and the rest are up to date (June 17 in my case).

**Comment by pd-l2ork** [comment]
On 06/19/2015 11:25 AM, muranyia wrote:
>
> Sure, open pd-l2ork, go to Edit, Preferences, GUI, click any color 
> button, change the color, click OK, the error appears in the console. 
> Close pd-l2ork, reopen it, the change you made is gone.
>
> I can confirm that pd.tk and the rest are up to date (June 17 in my case).
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pd-l2ork/pd/issues/23#issuecomment-113547839>.
>
Unfortunately, I am unable to recreate your problem here. Everything 
works on my computer as expected. Are you sure you installed the newly 
compiled version? Were there build errors in the process?

Relevant commits are:

https://github.com/pd-l2ork/pd/commit/c69509db7dd01a353e50da81cca7fa389541f594

https://github.com/pd-l2ork/pd/commit/89e541b471a033a367efe5f493102092e32c3c39

Please check your tcl files correspond with said changes. Also, please 
check what binary you may be invoking as you may have multiple pd-l2ork 
binaries installed (try pd-l2ork -version).

HTH

-- 
Ivica Ico Bukvic, D.M.A.
Associate Professor
Computer Music
ICAT Senior Fellow
DISIS, L2Ork
Virginia Tech
School of Performing Arts - 0141
Blacksburg, VA 24061
(540) 231-6139
ico@vt.edu
www.performingarts.vt.edu
disis.music.vt.edu
l2ork.music.vt.edu

**Comment by muranyia** [comment]
The changes are indeed missing from my version, albeit the file date is the same as the compilation date.

$ pd-l2ork -version
Pd-L2Ork version 20150617
compiled 21:47:53 Jun 17 2015

Shall I generate a build log then?

**Comment by pd-l2ork** [comment]
On 06/19/2015 11:31 PM, muranyia wrote:
>
> The changes are indeed missing from my version, albeit the file date 
> is the same as the compilation date.
>
> $ pd-l2ork -version
> Pd-L2Ork version 20150617
> compiled 21:47:53 Jun 17 2015
>
> Shall I generate a build log then?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pd-l2ork/pd/issues/23#issuecomment-113649769>.
>
Have you pulled latest changes? I don't think log will help--sounds like 
your git tree has not been updated. Try "git pull" inside the pd-l2ork 
folder and if that does not fix it, you can always pull a fresh version. HTH

-- 
Ivica Ico Bukvic, D.M.A.
Associate Professor
Computer Music
ICAT Senior Fellow
DISIS, L2Ork
Virginia Tech
School of Performing Arts - 0141
Blacksburg, VA 24061
(540) 231-6139
ico@vt.edu
www.performingarts.vt.edu
disis.music.vt.edu
l2ork.music.vt.edu

**Comment by muranyia** [comment]
Ah I see. I've been doing `git stash`, `git pull` as per the [instructions for Compiling Pd-L2Ork from Source](http://l2ork.music.vt.edu/main/?page_id=56#install-dev). Now I did just `git pull` and the changes got applied. Built fine, works fine.

I'm wondering: my `git stash list` still has 26 changes (not by me), what is the best way to clean it up?

Thanks

**Comment by pd-l2ork** [comment]
If you did both commands (stash and pull) in the same line, you should use
&& in between them. Beyond that, stash merely stashes any changes on your
end that may prevent automatic pulling.

HTH

**Comment by muranyia** [comment]
No, I did them on separate lines, of course. It seems that for some reason more files got dirty than necessary (maybe when I changed HDD->SSD and copied the disk over?) and then many changes did not get pulled.

So, momentarily I have 26 `WIP on master` stashes, shall I clear them, pop them, or leave them as they are?

**Comment by pd-l2ork** [comment]
Leave them as they are and git pull latest updates.
