### ISSUE TITLE
installation pdl2ork problem on debian 8

### ISSUE THREAD

**Issue by jcsekinger** [pd-l2ork/pd#24]
http://pastebin.com/5BeWj4Cc
what can I do please?

**Comment by pd-l2ork** [comment]
Hi,

You can uninstall Gem library for pd-extended, or install one of the 
packages Albert Graef put together on the launchpad that makes sure to 
omit anything that may collide with any of the pd-vanilla and/or 
pd-extended packages. For more info on Albert Graef's launchpad, please 
check the l2ork-dev mailing list's archives.

Hope this helps!

Best,

Ico

On 5/31/2015 7:42 AM, jcsekinger wrote:
>
> http://pastebin.com/5BeWj4Cc
> what can I do please?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pd-l2ork/pd/issues/24>.
>

-- 
Ivica Ico Bukvic, D.M.A.
Associate Professor
Computer Music
ICAT Senior Fellow
Director -- DISIS, L2Ork
Virginia Tech
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
ico@vt.edu
www.performingarts.vt.edu
disis.icat.vt.edu
l2ork.icat.vt.edu

**Comment by jcsekinger** [comment]
Thank you
Is it that page you were talking about: 
http://disis.music.vt.edu/pipermail/l2ork-dev/?

should I (try to) compile that version? https://github.com/pd-l2ork/pd

**Comment by pd-l2ork** [comment]
Yes, that is the mailing list URL. You probably don't need to compile 
anything if you can install Albert Graef's debs from his launchpad (I 
believe the URL is 
https://launchpad.net/~dr-graef/+archive/ubuntu/pd-l2ork and should 
contain builds for most recent Ubutu builds beyond 12.04).

Hope this helps!

Best,

Ico

On 6/3/2015 1:33 AM, jcsekinger wrote:
> Thank you
> Is it that page you were talking about:
> http://disis.music.vt.edu/pipermail/l2ork-dev/?
>
> should I (try to) compile that version? https://github.com/pd-l2ork/pd
>
>
> Le 02/06/2015 22:11, Pd-L2Ork a écrit :
> > Hi,
> >
> > You can uninstall Gem library for pd-extended, or install one of the
> > packages Albert Graef put together on the launchpad that makes sure to
> > omit anything that may collide with any of the pd-vanilla and/or
> > pd-extended packages. For more info on Albert Graef's launchpad, please
> > check the l2ork-dev mailing list's archives.
> >
> > Hope this helps!
> >
> > Best,
> >
> > Ico
> >
> > On 5/31/2015 7:42 AM, jcsekinger wrote:
> > >
> > > http://pastebin.com/5BeWj4Cc
> > > what can I do please?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/pd-l2ork/pd/issues/24>.
> > >
> >
> > --
> > Ivica Ico Bukvic, D.M.A.
> > Associate Professor
> > Computer Music
> > ICAT Senior Fellow
> > Director -- DISIS, L2Ork
> > Virginia Tech
> > School of Performing Arts – 0141
> > Blacksburg, VA 24061
> > (540) 231-6139
> > ico@vt.edu
> > www.performingarts.vt.edu
> > disis.icat.vt.edu
> > l2ork.icat.vt.edu
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/pd-l2ork/pd/issues/24#issuecomment-108082590>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pd-l2ork/pd/issues/24#issuecomment-108197811>.
>

-- 
Ivica Ico Bukvic, D.M.A.
Associate Professor
Computer Music
ICAT Senior Fellow
Director -- DISIS, L2Ork
Virginia Tech
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
ico@vt.edu
www.performingarts.vt.edu
disis.icat.vt.edu
l2ork.icat.vt.edu

**Comment by pd-l2ork** [comment]
Sorry, this is the latest 14.04 build place

https://launchpad.net/~dr-graef/+archive/ubuntu/pd-l2ork.trusty

HTH

On 6/6/2015 12:45 PM, Ivica Ico Bukvic wrote:
> Yes, that is the mailing list URL. You probably don't need to compile 
> anything if you can install Albert Graef's debs from his launchpad (I 
> believe the URL is 
> https://launchpad.net/~dr-graef/+archive/ubuntu/pd-l2ork and should 
> contain builds for most recent Ubutu builds beyond 12.04).
>
> Hope this helps!
>
> Best,
>
> Ico
>
> On 6/3/2015 1:33 AM, jcsekinger wrote:
>> Thank you
>> Is it that page you were talking about:
>> http://disis.music.vt.edu/pipermail/l2ork-dev/?
>>
>> should I (try to) compile that version? https://github.com/pd-l2ork/pd
>>
>>
>> Le 02/06/2015 22:11, Pd-L2Ork a écrit :
>> > Hi,
>> >
>> > You can uninstall Gem library for pd-extended, or install one of the
>> > packages Albert Graef put together on the launchpad that makes sure to
>> > omit anything that may collide with any of the pd-vanilla and/or
>> > pd-extended packages. For more info on Albert Graef's launchpad, please
>> > check the l2ork-dev mailing list's archives.
>> >
>> > Hope this helps!
>> >
>> > Best,
>> >
>> > Ico
>> >
>> > On 5/31/2015 7:42 AM, jcsekinger wrote:
>> > >
>> > > http://pastebin.com/5BeWj4Cc
>> > > what can I do please?
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <https://github.com/pd-l2ork/pd/issues/24>.
>> > >
>> >
>> > --
>> > Ivica Ico Bukvic, D.M.A.
>> > Associate Professor
>> > Computer Music
>> > ICAT Senior Fellow
>> > Director -- DISIS, L2Ork
>> > Virginia Tech
>> > School of Performing Arts – 0141
>> > Blacksburg, VA 24061
>> > (540) 231-6139
>> > ico@vt.edu
>> > www.performingarts.vt.edu
>> > disis.icat.vt.edu
>> > l2ork.icat.vt.edu
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/pd-l2ork/pd/issues/24#issuecomment-108082590>.
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub 
>> <https://github.com/pd-l2ork/pd/issues/24#issuecomment-108197811>.
>>
>
> -- 
> Ivica Ico Bukvic, D.M.A.
> Associate Professor
> Computer Music
> ICAT Senior Fellow
> Director -- DISIS, L2Ork
> Virginia Tech
> School of Performing Arts – 0141
> Blacksburg, VA 24061
> (540) 231-6139
> ico@vt.edu
> www.performingarts.vt.edu
> disis.icat.vt.edu
> l2ork.icat.vt.edu

-- 
Ivica Ico Bukvic, D.M.A.
Associate Professor
Computer Music
ICAT Senior Fellow
Director -- DISIS, L2Ork
Virginia Tech
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
ico@vt.edu
www.performingarts.vt.edu
disis.icat.vt.edu
l2ork.icat.vt.edu

**Comment by jcsekinger** [comment]
Tank you
but in debian 8 libmagick++-6 is installed and 
pd-l2ork(https://launchpad.net/~dr-graef/+archive/ubuntu/pd-l2ork.trusty/+build/7447898) 
ask for libmagick++-5

**Comment by pd-l2ork** [comment]
It is not pd-l2ork that asks for libmagick++5 but it is Gem library.
IOhannes provided a suggested fix on the pd list for this problem, although
this does not address pd-l2ork that has everything packaged together. See:

http://lists.puredata.info/pipermail/pd-list/2015-05/110201.html

I guess the easiest thing for you would be to build your own package (since
I don't have newer Ubuntu lying around). Please follow instructions on our
website--it only requires 3 commands to make your own package.

Hope this helps!

**Comment by agraef** [comment]
jcsekinger, if you don't need a proper Debian package, the easiest way is to build from source like this:

    cd l2ork_addons
    ./tar_em_up.sh -F

This will leave a tarball somewhere which can be extracted under / and installs everything under /usr/local.

You can also build a Debian package like this:

    ./tar_em_up.sh -B

(You might have to fix up a few dependencies in the control file under packages/linux_make/debian.)

Alternatively, you might want a look at my Debian packaging stuff that's in the debuild folder in the sources. This is the same stuff that I use to build the pd-l2ork packages I have on Launchpad. Instructions on how to use this can be found in debuild/Makefile, there's also a recent thread on the mailing list about this: http://disis.music.vt.edu/pipermail/l2ork-dev/2015-May/000724.html

**Comment by jcsekinger** [comment]
I did it (avec succès) Thank you :)

**Comment by pd-l2ork** [comment]
BTW, latest git commits now remove all offending files that may potentially clash with vanilla and extended, as well as update libmagick et al. dependencies inside deb to make it more flexible. HTH
