### ISSUE TITLE
Include [text] object

### ISSUE THREAD

**Issue by hellocatfood** [pd-l2ork/pd#31]
The [text] object was introduced into PD Vanilla in 0.45. It has many benefits over objects like [textfile], one being that it can handle multi line text. Can this object be added to PD-l2ork?

**Comment by pd-l2ork** [comment]
There is definitely a plan to do this. My initial goal was to wait until most of the bugs are worked out before introducing it into the pd-l2ork ecosystem. If you believe the object has reached the necessary stability, I'll gladly add it.

**Comment by hellocatfood** [comment]
As far as I can tell the object seems stable. I only need it to run this abstraction to have text on multiple lines http://lists.puredata.info/pipermail/pd-list/2015-06/110662.html (previously I had used this hack http://www.hellocatfood.com/text-on-multiple-lines-in-pure-data/

**Comment by pd-l2ork** [comment]
Cool. Let me look into adding it in the next release. Are there any 
other new objects you think we should have? There is no reason we 
shouldn't other than ensuring they are stable.

Best,

Ico

**Comment by pd-l2ork** [comment]
Latest version is now up to date with 0.47 vanilla branch.
