### ISSUE TITLE
cyclone externals not working after miXed update

### ISSUE THREAD

**Issue by agraef** [pd-l2ork/pd#34]
Since the external/miXed stuff is included as a submodule now, some of the cyclone externals such as `seq` stopped working, because the latest cyclone source uses `sys_fopen` which pd-l2ork doesn't have. Symptom: The externals will compile ok but refuse to load because of a runtime linker error:

~~~
/usr/lib/pd-l2ork/extra/cyclone/seq.pd_linux: /usr/lib/pd-l2ork/extra/cyclone/seq.pd_linux: undefined symbol: sys_fopen
 seq
... couldn't create
~~~

So either the cyclone sources need to be patched (which is what I'm doing in the Arch PKGBUILD right now) or pd-l2ork's m_pd.h header file needs to include at least dummy versions of these routines (`sys_open`, `sys_close`, `sys_fopen`, `sys_fclose`, full prototypes can be found in the vanilla m_pd.h file). Just defining these (`#define sys_fopen fopen` etc.) should probably do the trick for Linux, but for Jonathan's Windows port at least it will be necessary to backport the full definitions from vanilla Pd.

**Comment by pd-l2ork** [comment]
sys calls have been merged and this should be now working ok.
