### ISSUE TITLE
all gpio outputs won't work...

### ISSUE THREAD

**Issue by bltzr** [pd-l2ork/pd#42]
Hi there !

This is actually a question rather than a bug report, as I'm not sure at all your code is to blame (I also tested compiling the softPwm example from WiringPi , and got the same result.... - and found no wiringPi, nor pd-l2ork forum)
Despite having tried different things (like enabling/disabling the deviceTree), I still can't get most outputs to work on my Pis - BTW I have tested with a Pi2 and a Pi3, which give the same result.

**I only manage to have outputs 18, 22, 23 and 24 (BCM numbers) to actually work with pwm.**

Do others here have the same behavior ?

Also, do you know if the Pi>=2-specific outputs (i.e. physical pins 29 to 40) work with WiringPi ? It doesn't seem like it...

Thanks in advance for your insight !

Cheers, 

Pascal

**Comment by bltzr** [comment]
Of course, this happens using disis_gpio - sorry I forgot to mention it

**Comment by pd-l2ork** [comment]
Thank you for the report. I am not sure why you are encountering the 
said problem. What version are you using? We just finished a maker camp 
where we used 3rd generation RPis and encountered no problems you spoke 
of. That said, we did use the latest version that was built only a few 
weeks ago, so I wonder if the commit to the bug may have come after the 
latest formal release. Hope this helps!

Best,

Ico

**Comment by bltzr** [comment]
Hi ! I compiled just this external from source, after pulling from the repository... So maybe there's some conflict somewhere in my system, so I'll try to do a fresh install of pd-l2ork, and to try again from there... I'll let you know how it turns out... thanks !

**Comment by pd-l2ork** [comment]
This may be a stupid question. Are you starting pd-l2ork with sudo
privileges? When compiling your own version, the script pulls from the the
latest WiringPi git. Perhaps the latest WiringPI may have a regression in
it?

-- 
Ivica Ico Bukvic, D.M.A.
Associate Professor
Computer Music
ICAT Senior Fellow
Director -- DISIS, L2Ork
Virginia Tech
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
ico@vt.edu
www.performingarts.vt.edu
disis.icat.vt.edu
l2ork.icat.vt.edu
ico.bukvic.net

**Comment by bltzr** [comment]
Well, actually, I'm not using pd-l2ork at all, just disis_gpio (with pd-vanilla) and, yes, I'm starting pd with sudo...
also, I've reset my SD card to the latest backup, and now, for some reason it works... well for pins 4,  17, 18, 22, 23, 24, 25, 27 (haven't tried 7 & 8 as I'm using SPI for something else (APA102 LEDs), so I'm afraid that might interfere...)
So far so good...

What puzzles me is that I can't find any way to use the other GPIO's, that have been added from Rev.2, i.e. 5, 6, 12,13, 16, 19, 20, 21 - I have tried to add them to the cases in disis_gpio_isvalidpin, and recompile, but that doesn't seem to make the trick... any hint ?

**Comment by bltzr** [comment]
BTW, speaking of using pd-l2ork, I tried several times to use the [PdPi](http://pd-la.info/pdpi/) image that you recommend, but wasn't able to make it work on my Pi2... it just won't start up... well well...

**Comment by pd-l2ork** [comment]
Sounds like something was misconfigured with your setup. Regarding
additional pins, are you sure those should be accessible as general GPIOs?
Softpwm in part leverages WiringPi, so if it is not accessible there, it
won't be in pd-l2Ork either. When you get a chance, would you please close
this ticket? Thank you.

-- 
Ivica Ico Bukvic, D.M.A.
Associate Professor
Computer Music
ICAT Senior Fellow
Director -- DISIS, L2Ork
Virginia Tech
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
ico@vt.edu
www.performingarts.vt.edu
disis.icat.vt.edu
l2ork.icat.vt.edu
ico.bukvic.net

**Comment by bltzr** [comment]
Sure, I can close this ticket right now.  
And yes, this most probably has to do with WiringPi rather than directly pd-l2ork (as I stated from the start...)
Do you want me to let you know if I manage to make the extra outputs work ?

**Comment by bltzr** [comment]
Thanks for your help, BTW

**Comment by pd-l2ork** [comment]
Please do. Thank you.

-- 
Ivica Ico Bukvic, D.M.A.
Associate Professor
Computer Music
ICAT Senior Fellow
Director -- DISIS, L2Ork
Virginia Tech
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
ico@vt.edu
www.performingarts.vt.edu
disis.icat.vt.edu
l2ork.icat.vt.edu
ico.bukvic.net

**Comment by pd-l2ork** [comment]
That is because the image is for the older version of Pi (arm6). You should
still be able to install the actual Debian package onto a newer version of
Raspbian and make it work. Please let me know if you have attempted this
and it worked. Thank you.

-- 
Ivica Ico Bukvic, D.M.A.
Associate Professor
Computer Music
ICAT Senior Fellow
Director -- DISIS, L2Ork
Virginia Tech
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
ico@vt.edu
www.performingarts.vt.edu
disis.icat.vt.edu
l2ork.icat.vt.edu
ico.bukvic.net

**Comment by bltzr** [comment]
OK, got it to finally work, thanks to [this discussion](https://www.raspberrypi.org/forums/viewtopic.php?t=86297&p=610395)
I had to (manually, for now...) change the gpio modes of the extra outputs (gpio mode n out - n being numbered in the wiringPi fashion), and then I added the missing cases to disis_gpio.c, i.e. it now looks like this:
        case 4:
        case 5:
        case 6:
        case 7:
        case 8:
        case 12:
        case 13:
        case 16:
        case 17:
        case 18:
        case 19:
        case 20:
        case 21:
        case 22:
        case 23:
        case 24:
        case 25:
        case 27:

**Comment by bltzr** [comment]
re: the pdpi image, that would be worth mentioning on the pd-l2ork rPi page, in order to save the hassle to future users...

**Comment by bltzr** [comment]
I'll try to test the debian package if I have the time, which is very unsure...

**Comment by pd-l2ork** [comment]
BTW,

Would you please send a patch for this, so that I can merge it with the 
current external (if you are not comfortable creating a patch, just send 
the current source version)? Thank you.

Best,

Ico

**Comment by bltzr** [comment]
I'll do when I have it working consistently, which is not the case yet

**Comment by pd-l2ork** [comment]
Thank you.

**Comment by bltzr** [comment]
Hi ! Finally, that was quite simple once I got rid of the several conflicting versions I had on my drive...
You just have to replace the appropriate part with this in disis_gpio.c (just adding a few more cases):

```
static int disis_gpio_isvalidpin(int pin) {
    int ret;
    switch (pin) {
        case 0:
            ret = 1;
            break;
        case 4:
        case 5:
        case 6:
        case 7:
        case 8:
        case 12:
        case 13:
        case 16:
        case 17:
        case 18:
        case 19:
        case 20:
        case 21:
        case 22:
        case 23:
        case 24:
        case 25:
        case 27:
            ret = 2;
            break;
        default:
            ret = 0;
            post("disis_gpio: invalid pine number");
            break;
    }
    return(ret);
}
```

**Comment by pd-l2ork** [comment]
Thank you for sharing.
