### ISSUE TITLE
Fix fluid~ object in Purr Data on Windows

### ISSUE THREAD

**Issue by RichardJECooke** [pd-l2ork/pd#49]
I'm not sure if I should log this bug here or on GitLab: https://git.purrdata.net/jwilkes/purr-data/issues/540

I installed Purr Data (2.9.0 20190416-rev.2b3f27c1) on Windows 10 to try use a soundfont in Pure Data.

But when I try to open the the `C:\Program Files (x86)\Purr Data\extra\fluid~\fluid~\help.pd` help file I get the `couldn't create` error shown below. Other externals help files seem to load fine.
Is there anything I can do about this myself before the bug is fixed please?

![Untitled](https://user-images.githubusercontent.com/5468805/57103872-32815680-6d27-11e9-80ae-a5b788459cf7.png)

**Comment by agraef** [comment]
@RichardJECooke, this was recently fixed upstream, cf. https://git.purrdata.net/jwilkes/purr-data/issues/540, so it will be in the next Purr Data release. In the meantime you can find a workaround in the linked bug report.
