### ISSUE TITLE
Sources don't compile with gcc10 (on Arch)

### ISSUE THREAD

**Issue by agraef** [pd-l2ork/pd#59]
This seems to be the same kind of snag that we've recently encountered with purr-data, too, but which Jonathan has since fixed. With gcc10, while trying to link the pd-l2ork executable, I'm getting a lot of linkage errors of this kind:

~~~
[  381s] cd ../obj;  cc -Wl,-export-dynamic -lasound -lrt -ljack -lfftw3  -o ../bin/pd-l2ork d_ctl.o d_array.o d_delay.o d_filter.o d_math.o d_osc.o d_soundfile.o g_canvas.o g_graph.o g_text.o g_rtext.o g_array.o g_template.o g_io.o g_scalar.o g_traversal.o g_guiconnect.o g_readwrite.o g_editor.o g_clone.o g_undo.o g_all_guis.o g_bang.o g_mycanvas.o g_numbox.o g_toggle.o g_vumeter.o g_magicglass.o g_radio.o g_slider.o m_pd.o m_class.o m_obj.o m_atom.o m_memory.o m_binbuf.o m_conf.o m_glob.o m_sched.o s_main.o s_inter.o s_file.o s_print.o s_loader.o s_path.o s_entry.o s_audio.o s_midi.o s_utf8.o d_ugen.o d_arithmetic.o d_dac.o d_misc.o d_fft.o d_global.o d_resample.o x_arithmetic.o x_connective.o x_interface.o x_midi.o x_misc.o x_time.o x_acoustics.o x_net.o x_text.o x_gui.o x_list.o x_array.o x_preset.o x_scalar.o x_vexp.o x_vexp_if.o x_vexp_fun.o import.o s_midi_oss.o s_audio_oss.o s_audio_alsa.o s_audio_alsamm.o s_midi_alsa.o s_audio_jack.o d_fft_fftw.o d_fftroutine.o  -ldl -lm -lpthread -lfftw3f -lasound -ljack -ljack
[  382s] /usr/bin/ld: g_graph.o:/usr/src/packages/BUILD/pd-l2ork/src/pd-l2ork-20190812+git1771+42cedfa8/pd/src/g_canvas.h:635: multiple definition of `array_joc'; g_canvas.o:/usr/src/packages/BUILD/pd-l2ork/src/pd-l2ork-20190812+git1771+42cedfa8/pd/src/g_canvas.h:635: first defined here
[  382s] /usr/bin/ld: g_graph.o:/usr/src/packages/BUILD/pd-l2ork/src/pd-l2ork-20190812+git1771+42cedfa8/pd/src/s_stuff.h:21: multiple definition of `pd_extrapath'; g_canvas.o:/usr/src/packages/BUILD/pd-l2ork/src/pd-l2ork-20190812+git1771+42cedfa8/pd/src/s_stuff.h:21: first defined here
... many more messages like these ...
[  383s] collect2: error: ld returned 1 exit status
[  383s] make[2]: *** [makefile:185: ../bin/pd-l2ork] Error 1
[  383s] make[2]: Leaving directory '/usr/src/packages/BUILD/pd-l2ork/src/pd-l2ork-20190812+git1771+42cedfa8/pd/src'
~~~

The full buildlog can be found at the OBS here: https://build.opensuse.org/build/home:aggraef/Arch/x86_64/pd-l2ork/_log. (I was building an older revision there, but it's the same error with the current HEAD.)

If you sift through the commit log of purr-data, you can probably find Jonathan's fixes and apply something similar here.

**Comment by agraef** [comment]
Same error on openSUSE Tumbleweed ([buildlog](https://build.opensuse.org/build/home:aggraef/openSUSE_Tumbleweed/x86_64/pd-l2ork/_log)). Which was to be expected, since it's also a rolling release, so presumably it has gcc10 as well.

Somewhat surprisingly, the builds still succeed on Debian Testing and Unstable, so it seems that these are still using an older gcc for now. But I expect that the problem surfaces there as well once they update to gcc10.

I should add that all stable Debian and Ubuntu releases still work fine for now. It looks like the upcoming Ubuntu 20.10 still uses gcc 9 (9.3) as well, so we should be good there, too, once I start building packages for it.

For now, we're good on Arch and Tumbleweed as well, because I still have old pd-l2ork packages in those repos which were built before the upgrade to gcc10 happened. But these are from May, and they *will* break at some point, i.e., as soon as one of the dependencies has an update which breaks binary compatibility and thus needs a recompile. So it would certainly be helpful if this bug could be fixed asap, so that these builds work again.

Summary of build results is available at https://build.opensuse.org/project/show/home:aggraef.

**Comment by agraef** [comment]
Just to be clear, the problem with gcc10 is that the new version is a lot pickier when linking and will downright refuse to link binaries if there's more than one definition for a symbol in the linked modules.

And here are Jonathan's commits in purr-data which I think fixed this bug (links to my GH mirror for convenience):

https://github.com/agraef/purr-data/commit/0317d79ab80de57676f111569e4de48ef246a1e6 fix some global vars erroneously declared in headers and other places
https://github.com/agraef/purr-data/commit/522817b63f082b5e698b333fdfed58a79625e1ea fix lingering error with a multiply-defined global variable
https://github.com/agraef/purr-data/commit/5a72365e37c1d4dad8030351b0b508e0bcfe0efc more fixes for multiply defined global variables

Note that those lines 35 and 36 in https://github.com/agraef/purr-data/commit/0317d79ab80de57676f111569e4de48ef246a1e6 are actually wrong (not even valid C), they then just got removed in the next commit https://github.com/agraef/purr-data/commit/522817b63f082b5e698b333fdfed58a79625e1ea. But I listed all commits related to these changes so that they form a complete changeset (hopefully).

I can't say whether these changes all apply to pd-l2ork as well, and whether pd-l2ork may have more multiply defined symbols like these, as the code bases have diverged quite a bit by now. But this should at least give you an indication of what to look for.

**Comment by agraef** [comment]
For your convenience, here are all of Jonathan's changes (the net outcome of the three commits listed above) taken together. I don't expect these to apply to pd-l2ork unchanged, but you can always give it the good old college try. ;-)

Stupid GH doesn't let me attach a diff file here, so there it goes as inline text:

~~~diff
diff --git a/externals/iem/iem_adaptfilt/src/iemlib.h b/externals/iem/iem_adaptfilt/src/iemlib.h
index 97b088ba..9bf866b1 100644
--- a/externals/iem/iem_adaptfilt/src/iemlib.h
+++ b/externals/iem/iem_adaptfilt/src/iemlib.h
@@ -22,11 +22,11 @@ iemlib written by Thomas Musil, Copyright (c) IEM KUG Graz Austria 2000 - 2009 *
  */
 
 #ifdef MSW
-int sys_noloadbang;
+//int sys_noloadbang;
 //t_symbol *iemgui_key_sym=0;
 #include <io.h>
 #else
-extern int sys_noloadbang;
+//extern int sys_noloadbang;
 //extern t_symbol *iemgui_key_sym;
 #include <unistd.h>
 #endif
diff --git a/externals/iem/iem_ambi/src/iemlib.h b/externals/iem/iem_ambi/src/iemlib.h
index 97b088ba..9bf866b1 100644
--- a/externals/iem/iem_ambi/src/iemlib.h
+++ b/externals/iem/iem_ambi/src/iemlib.h
@@ -22,11 +22,11 @@ iemlib written by Thomas Musil, Copyright (c) IEM KUG Graz Austria 2000 - 2009 *
  */
 
 #ifdef MSW
-int sys_noloadbang;
+//int sys_noloadbang;
 //t_symbol *iemgui_key_sym=0;
 #include <io.h>
 #else
-extern int sys_noloadbang;
+//extern int sys_noloadbang;
 //extern t_symbol *iemgui_key_sym;
 #include <unistd.h>
 #endif
diff --git a/externals/iem/iem_atan2/src/iemlib.h b/externals/iem/iem_atan2/src/iemlib.h
index 97b088ba..9bf866b1 100644
--- a/externals/iem/iem_atan2/src/iemlib.h
+++ b/externals/iem/iem_atan2/src/iemlib.h
@@ -22,11 +22,11 @@ iemlib written by Thomas Musil, Copyright (c) IEM KUG Graz Austria 2000 - 2009 *
  */
 
 #ifdef MSW
-int sys_noloadbang;
+//int sys_noloadbang;
 //t_symbol *iemgui_key_sym=0;
 #include <io.h>
 #else
-extern int sys_noloadbang;
+//extern int sys_noloadbang;
 //extern t_symbol *iemgui_key_sym;
 #include <unistd.h>
 #endif
diff --git a/externals/iem/iem_bin_ambi/src/iemlib.h b/externals/iem/iem_bin_ambi/src/iemlib.h
index 97b088ba..9bf866b1 100644
--- a/externals/iem/iem_bin_ambi/src/iemlib.h
+++ b/externals/iem/iem_bin_ambi/src/iemlib.h
@@ -22,11 +22,11 @@ iemlib written by Thomas Musil, Copyright (c) IEM KUG Graz Austria 2000 - 2009 *
  */
 
 #ifdef MSW
-int sys_noloadbang;
+//int sys_noloadbang;
 //t_symbol *iemgui_key_sym=0;
 #include <io.h>
 #else
-extern int sys_noloadbang;
+//extern int sys_noloadbang;
 //extern t_symbol *iemgui_key_sym;
 #include <unistd.h>
 #endif
diff --git a/externals/iem/iem_delay/src/iemlib.h b/externals/iem/iem_delay/src/iemlib.h
index 97b088ba..9bf866b1 100644
--- a/externals/iem/iem_delay/src/iemlib.h
+++ b/externals/iem/iem_delay/src/iemlib.h
@@ -22,11 +22,11 @@ iemlib written by Thomas Musil, Copyright (c) IEM KUG Graz Austria 2000 - 2009 *
  */
 
 #ifdef MSW
-int sys_noloadbang;
+//int sys_noloadbang;
 //t_symbol *iemgui_key_sym=0;
 #include <io.h>
 #else
-extern int sys_noloadbang;
+//extern int sys_noloadbang;
 //extern t_symbol *iemgui_key_sym;
 #include <unistd.h>
 #endif
diff --git a/externals/iem/iem_matrix/src/iemlib.h b/externals/iem/iem_matrix/src/iemlib.h
index 97b088ba..9bf866b1 100644
--- a/externals/iem/iem_matrix/src/iemlib.h
+++ b/externals/iem/iem_matrix/src/iemlib.h
@@ -22,11 +22,11 @@ iemlib written by Thomas Musil, Copyright (c) IEM KUG Graz Austria 2000 - 2009 *
  */
 
 #ifdef MSW
-int sys_noloadbang;
+//int sys_noloadbang;
 //t_symbol *iemgui_key_sym=0;
 #include <io.h>
 #else
-extern int sys_noloadbang;
+//extern int sys_noloadbang;
 //extern t_symbol *iemgui_key_sym;
 #include <unistd.h>
 #endif
diff --git a/externals/iem/iem_roomsim/src/iemlib.h b/externals/iem/iem_roomsim/src/iemlib.h
index 97b088ba..9bf866b1 100644
--- a/externals/iem/iem_roomsim/src/iemlib.h
+++ b/externals/iem/iem_roomsim/src/iemlib.h
@@ -22,11 +22,11 @@ iemlib written by Thomas Musil, Copyright (c) IEM KUG Graz Austria 2000 - 2009 *
  */
 
 #ifdef MSW
-int sys_noloadbang;
+//int sys_noloadbang;
 //t_symbol *iemgui_key_sym=0;
 #include <io.h>
 #else
-extern int sys_noloadbang;
+//extern int sys_noloadbang;
 //extern t_symbol *iemgui_key_sym;
 #include <unistd.h>
 #endif
diff --git a/externals/iem/iem_spec2/src/iemlib.h b/externals/iem/iem_spec2/src/iemlib.h
index ac1ffced..38021322 100644
--- a/externals/iem/iem_spec2/src/iemlib.h
+++ b/externals/iem/iem_spec2/src/iemlib.h
@@ -25,11 +25,11 @@ iemlib written by Thomas Musil, Copyright (c) IEM KUG Graz Austria 2000 - 2012 *
  */
 
 #ifdef MSW
-int sys_noloadbang;
+//int sys_noloadbang;
 //t_symbol *iemgui_key_sym=0;
 #include <io.h>
 #else
-extern int sys_noloadbang;
+//extern int sys_noloadbang;
 //extern t_symbol *iemgui_key_sym;
 #include <unistd.h>
 #endif
diff --git a/externals/iem/iem_tab/src/iemlib.h b/externals/iem/iem_tab/src/iemlib.h
index ac1ffced..38021322 100644
--- a/externals/iem/iem_tab/src/iemlib.h
+++ b/externals/iem/iem_tab/src/iemlib.h
@@ -25,11 +25,11 @@ iemlib written by Thomas Musil, Copyright (c) IEM KUG Graz Austria 2000 - 2012 *
  */
 
 #ifdef MSW
-int sys_noloadbang;
+//int sys_noloadbang;
 //t_symbol *iemgui_key_sym=0;
 #include <io.h>
 #else
-extern int sys_noloadbang;
+//extern int sys_noloadbang;
 //extern t_symbol *iemgui_key_sym;
 #include <unistd.h>
 #endif
diff --git a/externals/iem/iemgui/src/iemlib.h b/externals/iem/iemgui/src/iemlib.h
index 97b088ba..9bf866b1 100644
--- a/externals/iem/iemgui/src/iemlib.h
+++ b/externals/iem/iemgui/src/iemlib.h
@@ -22,11 +22,11 @@ iemlib written by Thomas Musil, Copyright (c) IEM KUG Graz Austria 2000 - 2009 *
  */
 
 #ifdef MSW
-int sys_noloadbang;
+//int sys_noloadbang;
 //t_symbol *iemgui_key_sym=0;
 #include <io.h>
 #else
-extern int sys_noloadbang;
+//extern int sys_noloadbang;
 //extern t_symbol *iemgui_key_sym;
 #include <unistd.h>
 #endif
diff --git a/externals/iemlib/include/iemlib.h b/externals/iemlib/include/iemlib.h
index ac1ffced..38021322 100644
--- a/externals/iemlib/include/iemlib.h
+++ b/externals/iemlib/include/iemlib.h
@@ -25,11 +25,11 @@ iemlib written by Thomas Musil, Copyright (c) IEM KUG Graz Austria 2000 - 2012 *
  */
 
 #ifdef MSW
-int sys_noloadbang;
+//int sys_noloadbang;
 //t_symbol *iemgui_key_sym=0;
 #include <io.h>
 #else
-extern int sys_noloadbang;
+//extern int sys_noloadbang;
 //extern t_symbol *iemgui_key_sym;
 #include <unistd.h>
 #endif
diff --git a/pd/src/s_audio_mmio.c b/pd/src/s_audio_mmio.c
index 0ada2c23..6f27fe03 100644
--- a/pd/src/s_audio_mmio.c
+++ b/pd/src/s_audio_mmio.c
@@ -32,7 +32,6 @@ int nt_realdacblksize;
 #define MAXBUFFER 100   /* number of buffers in use at maximum advance */
 #define DEFBUFFER 30    /* default is about 30x6 = 180 msec! */
 static int nt_naudiobuffer = DEFBUFFER;
-t_float sys_dacsr = DEFAULTSRATE;
 
 static int nt_whichapi = API_MMIO;
 static int nt_meters;        /* true if we're metering */
@@ -128,6 +127,13 @@ int mmio_do_open_audio(void)
         post("%d devices in, %d devices out",
             nt_nwavein, nt_nwaveout);
 
+        /* quick check to make sure we've got a sane sys_dacsr. This file
+           initially redeclared sys_dacsr *and* redefined it to DEFAULTSRATE
+           in the global scope. That not valid C, so I'm just guessing at the
+           author's motives and conditionally setting to that default in this
+           function scope, right before sys_dacsr gets used in the code. */
+    if (sys_dacsr == 0) sys_dacsr = DEFAULTSRATE;
+
     form.wf.wFormatTag = WAVE_FORMAT_PCM;
     form.wf.nChannels = CHANNELS_PER_DEVICE;
     form.wf.nSamplesPerSec = sys_dacsr;
@@ -486,11 +492,6 @@ void nt_logerror(int which)
 #endif
 }
 
-/* system buffer with t_sample types for one tick */
-t_sample *sys_soundout;
-t_sample *sys_soundin;
-t_float sys_dacsr;
-
 int mmio_send_dacs(void)
 {
     HMMIO hmmio; 
@@ -723,7 +724,10 @@ int mmio_open_audio(int naudioindev, int *audioindev,
     nt_whichdac = (naudiooutdev < 1 ?
         (nt_nwaveout > 1 ? WAVE_MAPPER : -1) : audiooutdev[0]);
     if (naudiooutdev > 1 || naudioindev > 1)
- post("separate audio device choice not supported; using sequential devices.");
+    {
+        post("separate audio device choice not supported; "
+             "using sequential devices.");
+    }
     return (mmio_do_open_audio());
 }
 
diff --git a/pd/src/s_audio_oss.c b/pd/src/s_audio_oss.c
index c2153ab3..61718f47 100644
--- a/pd/src/s_audio_oss.c
+++ b/pd/src/s_audio_oss.c
@@ -67,11 +67,6 @@ static t_oss_dev linux_adcs[OSS_MAXDEV];
 static int linux_noutdevs = 0;
 static int linux_nindevs = 0;
 
-    /* exported variables */
-t_float sys_dacsr;
-t_sample *sys_soundout;
-t_sample *sys_soundin;
-
     /* OSS-specific private variables */
 static int oss_blockmode = 1;   /* flag to use "blockmode"  */
 
diff --git a/pd/src/s_path.c b/pd/src/s_path.c
index 3582626f..9b2aebb8 100644
--- a/pd/src/s_path.c
+++ b/pd/src/s_path.c
@@ -45,6 +45,7 @@ t_namelist *sys_searchpath;
 t_namelist *sys_staticpath;
 t_namelist *sys_helppath;
 
+t_namelist *pd_extrapath;
 
     /* change '/' characters to the system's native file separator */
 void sys_bashfilename(const char *from, char *to)
diff --git a/pd/src/s_stuff.h b/pd/src/s_stuff.h
index 0967e026..04b62b45 100644
--- a/pd/src/s_stuff.h
+++ b/pd/src/s_stuff.h
@@ -18,7 +18,7 @@ typedef struct _namelist    /* element in a linked list of stored strings */
     char *nl_string;            /* the string */
 } t_namelist;
 
-t_namelist *pd_extrapath;
+extern t_namelist *pd_extrapath;
 t_namelist *namelist_append(t_namelist *listwas, const char *s, int allowdup);
 t_namelist *namelist_append_files(t_namelist *listwas, const char *s);
 void namelist_free(t_namelist *listwas);
~~~

**Comment by brandflake11** [comment]
Hello,
Is this the same reason that pd-l2ork doesn't compile from the aur? I can post a log of that as well, and I posted an issue over on the [aur page for pd-l2ork](https://aur.archlinux.org/packages/pd-l2ork)?

**Comment by pd-l2ork** [comment]
Thank you, Albert.

Best,

Ico

-- 
Ivica Ico Bukvic, D.M.A.
Director, Creativity + Innovation
Institute for Creativity, Arts, and Technology

Virginia Tech
Creative Technologies in Music
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
ico@vt.edu

www.icat.vt.edu
www.performingarts.vt.edu
l2ork.icat.vt.edu
ico.bukvic.net

**Comment by agraef** [comment]
@brandflake11 Yes, I guess it is (it's hard to tell because your excerpt from the log doesn't show the real source of the error). I didn't reply there in the AUR comments yet, since so far there's no solution, so we have to wait that Ico fixes it.

**Comment by pd-l2ork** [comment]
Just to make sure, if one source has

int blah = 0;

and another has

extern int blah;

that should work? If so, I wonder how did the multiple defines get created
and passed under the radar until now? If not, how do we expect to share
vars across multiple sources?
Best,

Ico

-- 
Ivica Ico Bukvic, D.M.A.
Director, Creativity + Innovation
Director, Human-Centered Design iPhD
Institute for Creativity, Arts, and Technology

Virginia Tech
Creative Technologies in Music
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
ico@vt.edu

ci.icat.vt.eduhcd.icat.vt.eduwww.icat.vt.edu
www.performingarts.vt.edu
l2ork.icat.vt.edu
ico.bukvic.net

**Comment by agraef** [comment]
Yes, `extern int blah` just *declares* `blah` but doesn't *define* it, as `int blah` does. If you have multiple *definitions* of `blah` then you're in trouble now.

> If so, I wonder how did the multiple defines get created and passed under the radar until now?

Linkers used to be lenient about multiple definitions and just consolidate them into one. I'm not sure what the latest C standard says about this, but gcc 10 flags these as an error now. Here's the quote from https://gcc.gnu.org/gcc-10/porting_to.html:

# C language issues
## Default to -fno-common

A common mistake in C is omitting extern when declaring a global variable in a header file. If the header is included by several files it results in multiple definitions of the same variable. In previous GCC versions this error is ignored. GCC 10 defaults to `-fno-common`, which means a linker error will now be reported. To fix this, use extern in header files when declaring global variables, and ensure each global is defined in exactly one C file. If tentative definitions of particular variables need to be placed in a common block, `__attribute__((__common__))` can be used to force that behavior even in code compiled without `-fcommon`. As a workaround, legacy C code where all tentative definitions should be placed into a common block can be compiled with `-fcommon`.

~~~c
      int x;  // tentative definition - avoid in header files

      extern int y;  // correct declaration in a header file
~~~

**Comment by agraef** [comment]
As you can see, there are ways to work around this with compiler options and directives. But the fact remains that multiple definitions of the same global are usually bugs that need to be fixed. gcc 10 just makes that more obvious. :)

**Comment by pd-l2ork** [comment]
Understood. It appears that the conflicts are coming from the external
libraries that abuse internal definitions, or are simply poorly coded. by
the way, this shouldn't be too difficult to fix. Thank you for reporting
this. I will look into it as soon as possible.

Best,

Ico

-- 
Ivica Ico Bukvic, D.M.A.
Director, Creativity + Innovation
Institute for Creativity, Arts, and Technology

Virginia Tech
Creative Technologies in Music
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
ico@vt.edu

www.icat.vt.edu
www.performingarts.vt.edu
l2ork.icat.vt.edu
ico.bukvic.net

**Comment by agraef** [comment]
Thanks a bunch, looking forward to it. I'll test on Arch, and then update the AUR and OBS packages, so that Arch and Tumbleweed users will be fine again.
