### ISSUE TITLE
Status of Qt / QML port?

### ISSUE THREAD

**Issue by fferri** [pd-l2ork/pd#65]
In the README, under Contributors' guide, it is mentioned:

- porting Pd-L2Ork's graphical user interface from Tcl/Tk to Qt.
    - skills needed: knowledge about Qt5/QML, threading, and Pd's core design and deterministic message-dispatching and scheduling
    - status: under active development

I would like to know what's thew status of this task and where I can find more info. I have a lot of experience with Qt5 and QtQuick/QML, I've been making modern widgets for music/multimedia, and I could give some contribution.

**Comment by pd-l2ork** [comment]
Hi, and thanks for your interest. There is pd-l2ork 2.x version now that relies on nw.js. So, barring any unexpected developments regarding nw.js, it is unlikely I will be porting pd-l2ork to Qt. You can check out the other version at https://github.com/pd-l2ork/pd-l2ork

That said, if you are still interested in contributing to other aspects of the code, please do let me know.

**Comment by fferri** [comment]
Thanks for the quick reply.

May I ask you some pointers about how did you manage to integrate Pd with your UI, especially:
- dynamic patch modification (deleting objects, moving objects)
- introspection, i.e. how many inlets and outlets a box has?

I had developed a QML node editor long time ago for learning purposes. Recently I tried to integrate it with libpd [1], but the canvas has no builtin delete method, so I have to use [iemguts/canvasdelete] for that. No way to move a box anyways. And knowing the iolets count seems pure science fiction. Probably can be done with a ton of hacks :)

Here's the prototypical pd hello world being patched:
1: https://www.youtube.com/watch?v=WwQ-MYeTjiE

**Comment by pd-l2ork** [comment]
This looks fantastic. Perhaps we can integrate it into pd-l2ork? We can
always expose new hooks. I am not interested in supporting hacks that abuse
access to tcl/tk backend as that is unsustainable if one wishes to expand
the program's features. This is why also pd-l2ork can be easily expanded to
accommodate your specific needs, while ensuring that those hooks remain
available (and/or only accessible to your specific QML node editor).

Best,

Ico

-- 
Ivica Ico Bukvic, D.M.A.
Director, Creativity + Innovation
Director, Human-Centered Design iPhD
Institute for Creativity, Arts, and Technology

Virginia Tech
Creative Technologies in Music
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
***@***.***

ci.icat.vt.edu
l2ork.icat.vt.edu
ico.bukvic.net
